[package]
name = "pseudocode"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11" # version of the crate
tokio = { version = "1", features = ["full"]} # crate version of async runtime library